[package]
name = "advanced-notebook"
version = "1.0.0"
description = "Advanced Notebook"
authors = []
license = "MIT"
edition = "2021"
rust-version = "1.70"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "advanced-notebook"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1.0"
tauri        = { version = "1.5.0", features = [ "dialog-message", "dialog-open", "shell-open", "path-all", "fs-all"] }
tauri-plugin-sql = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1", features = ["sqlite"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
panic = "abort"
strip = true

[features]
custom-protocol = ["tauri/custom-protocol"]
